# Generated by Django 4.0.3 on 2022-03-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredients',
            options={'verbose_name': 'Ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='mealtag',
            options={'verbose_name': 'Категория блюда', 'verbose_name_plural': 'Категории блюд'},
        ),
        migrations.AlterModelOptions(
            name='restricttag',
            options={'verbose_name': 'Ограничение по меню', 'verbose_name_plural': 'Ограничения по меню'},
        ),
        migrations.AlterModelOptions(
            name='subscriptiontimeinterval',
            options={'verbose_name': 'Период подписки', 'verbose_name_plural': 'Периоды подписки'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Мера измерения', 'verbose_name_plural': 'Меры измерения'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='allergic',
        ),
        migrations.AddField(
            model_name='recipe',
            name='restriction',
            field=models.ManyToManyField(to='recipes.restricttag', verbose_name='Ограничение в меню'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='mealtag',
            name='meal',
            field=models.CharField(max_length=100, verbose_name='Приём пищи'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.AmountIngredients', to='recipes.ingredient', verbose_name='Ингредиенты в рецепте'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_text',
            field=models.TextField(blank=True, verbose_name='Описание приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='restricttag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='Ограничение по меню'),
        ),
        migrations.AlterField(
            model_name='subscriptiontimeinterval',
            name='time_intervals',
            field=models.PositiveIntegerField(verbose_name='Период посписки в месяцах'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Мера измерения'),
        ),
    ]
