# Generated by Django 4.0.3 on 2022-03-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_amountingredients_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='person_quantity',
            new_name='persons_num',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='restrict_tag',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='time_intervals',
        ),
        migrations.AddField(
            model_name='subscription',
            name='meals',
            field=models.ManyToManyField(blank=True, to='recipes.mealtag', verbose_name='Категории блюд'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='recipes.subscriptiontimeinterval', verbose_name='Длительность подписки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='restrict_tags',
            field=models.ManyToManyField(blank=True, to='recipes.restricttag', verbose_name='Ограничения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.unit', verbose_name='Мера измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes', verbose_name='Изображение к рецепту'),
        ),
    ]
