# Generated by Django 4.0.3 on 2022-03-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_meal_remove_recipe_restriction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredients',
            old_name='counts',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='amountingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='recipes.ingredient', verbose_name='ингредиент'),
        ),
        migrations.AlterField(
            model_name='amountingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='recipes.recipe', verbose_name='рецепт'),
        ),
    ]
