# Generated by Django 4.0.3 on 2022-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_counts_amountingredients_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_text',
            field=models.TextField(verbose_name='Описание приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='restrict_tags',
            field=models.ManyToManyField(blank=True, to='recipes.restricttag', verbose_name='Ограничения в меню'),
        ),
    ]
