# Generated by Django 4.0.3 on 2022-03-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_recipe_text_alter_recipe_restrict_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredients',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
