# Generated by Django 4.0.3 on 2022-03-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_amountingredients_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontimeinterval',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='цена за подписку'),
        ),
    ]
